# Generated by Django 5.2.4 on 2025-07-16 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfterPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('number', models.CharField(max_length=11)),
                ('payment_info', models.TextField(max_length=500)),
                ('way_to_pay', models.CharField(choices=[('paypal', 'PayPal'), ('direct', 'Direct')], default='direct', max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afterpay', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='afterpay', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
