# Generated by Django 5.2.4 on 2025-07-16 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_afterpay_way_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpay',
            name='way_to_pay',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('direct', 'Direct')], default='direct', max_length=10),
        ),
    ]
