# Generated by Django 5.2.4 on 2025-07-17 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_watchedvideo'),
        ('courses', '0008_remove_coursevideo_seen'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchedvideo',
            unique_together={('user', 'course', 'video')},
        ),
    ]
