# Generated by Django 5.2.4 on 2025-07-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_watchedvideo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruser',
            name='students',
            field=models.IntegerField(default=0),
        ),
    ]
