# Generated by Django 5.2.4 on 2025-07-18 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cartitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Course',
            new_name='course',
        ),
    ]
