# Generated by Django 5.2.4 on 2025-07-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterpay',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afterpay', to='accounts.cart'),
        ),
    ]
