# Generated by Django 5.2.4 on 2025-07-18 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_afterpay_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterpay',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='afterpay', to='accounts.cart'),
        ),
    ]
