# Generated by Django 5.2.4 on 2025-07-15 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('total_price', models.IntegerField(default=0)),
                ('total_hours', models.FloatField(blank=True, default=0, null=True)),
                ('rate', models.CharField(default='0', max_length=2)),
                ('language', models.CharField(blank=True, max_length=20, null=True)),
                ('level', models.CharField(blank=True, max_length=15, null=True)),
                ('Sessions', models.IntegerField(default=0)),
                ('info', models.TextField(blank=True, max_length=200, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='Thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('students', models.ManyToManyField(blank=True, related_name='course', to='accounts.profile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='accounts.teacheruser')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('info', models.TextField(blank=True, max_length=400, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='course-videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='videoes-thumbnails/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.FloatField(default=0)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.title')),
            ],
        ),
    ]
