# Generated by Django 5.2.4 on 2025-07-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=200)),
                ('mymodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.course')),
            ],
        ),
    ]
