# Generated by Django 5.2.4 on 2025-07-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
