# Generated by Django 5.2.4 on 2025-07-17 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_like_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
