# Generated by Django 5.2.4 on 2025-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='seen',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1')], default='0', max_length=1, null=True),
        ),
    ]
