# Generated by Django 5.2.4 on 2025-07-17 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursevideo_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='seen',
        ),
    ]
