# Generated by Django 5.2.4 on 2025-07-17 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_watchedvideo_unique_together'),
        ('courses', '0008_remove_coursevideo_seen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='accounts.profile')),
                ('vid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursevideo')),
            ],
        ),
    ]
