# Generated by Django 5.2.4 on 2025-07-17 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_coments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coments',
            name='vid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='courses.coursevideo'),
        ),
    ]
