# Generated by Django 5.2.4 on 2025-07-17 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_watchedvideo_unique_together'),
        ('courses', '0010_alter_coments_vid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coments',
            new_name='Comments',
        ),
    ]
