# Generated by Django 5.2.4 on 2025-07-18 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_teacheruser_students'),
        ('courses', '0011_rename_coments_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='responded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='RespondedComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=400)),
                ('comments', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='respond', to='courses.comments')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respond', to='accounts.teacheruser')),
            ],
        ),
    ]
