# Generated by Django 5.2.4 on 2025-07-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_comments_responded_respondedcomments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursevideo",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="course-videos/"),
        ),
    ]
